"use client";
import { useCallback, useMemo, useState } from "react";
import { addEdge, Background, Connection, Controls, Edge, MiniMap, Node, ReactFlow, ReactFlowProvider, useEdgesState, useNodesState, useReactFlow } from "@xyflow/react";

type Data = { label: string; nodeType: string; configuration: Record<string, unknown> };
const TYPES = ["manual_trigger","webhook_trigger","schedule_trigger","set","condition","http_request","postgresql","delay","merge","stop"];
const DEFAULTS: Record<string,Record<string,unknown>> = {
  webhook_trigger:{method:"POST",auth_type:"none"}, schedule_trigger:{cron:"*/5 * * * *",timezone:"UTC"},
  set:{values:{}}, condition:{expression:"$input.ok == true"}, http_request:{method:"GET",url:"https://example.com",timeout_seconds:30},
  postgresql:{query:"SELECT :value AS value",parameters:{value:"{{$input.value}}"},credential_id:""}, delay:{seconds:1}, merge:{mode:"wait_for_all"}
};
async function api(path:string, options:RequestInit={}) { const response=await fetch(path,{credentials:"include",...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}); const body=response.status===204?null:await response.json(); if(!response.ok) throw new Error(typeof body?.detail==="string"?body.detail:JSON.stringify(body?.detail||body)); return body; }

function Studio() {
  const [nodes,setNodes,onNodesChange]=useNodesState<Node<Data>>([]); const [edges,setEdges,onEdgesChange]=useEdgesState<Edge>([]);
  const [selected,setSelected]=useState<string|null>(null), [workflowId,setWorkflowId]=useState(""), [revision,setRevision]=useState(1);
  const [csrf,setCsrf]=useState(""), [email,setEmail]=useState("admin@flowapi.local"), [password,setPassword]=useState("");
  const [message,setMessage]=useState("Giriş yapın ve bir workflow kimliği yükleyin."), [execution,setExecution]=useState<Record<string,unknown>|null>(null);
  const {screenToFlowPosition}=useReactFlow(); const selectedNode=useMemo(()=>nodes.find(n=>n.id===selected),[nodes,selected]);
  const onConnect=useCallback((c:Connection)=>setEdges(es=>addEdge({...c,id:crypto.randomUUID(),sourceHandle:c.sourceHandle||"success",targetHandle:c.targetHandle||"input"},es)),[setEdges]);
  const graph=()=>({nodes:nodes.map(n=>({id:n.id,type:n.data.nodeType,version:1,configuration:n.data.configuration,position:n.position})),edges:edges.map(e=>({id:e.id,source_node_id:e.source,target_node_id:e.target,source_handle:e.sourceHandle||"success",target_handle:e.targetHandle||"input"}))});
  const login=async()=>{try{const r=await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({email,password})});setCsrf(r.csrf_token);setMessage("Oturum açıldı.");}catch(e){setMessage(String(e));}};
  const load=async()=>{try{const r=await api(`/api/v1/workflows/${workflowId}`);setRevision(r.draft_revision);setNodes(r.draft_definition.nodes.map((n:any)=>({id:n.id,position:n.position||{x:80,y:80},data:{label:n.type.replaceAll("_"," "),nodeType:n.type,configuration:n.configuration||{}}})));setEdges(r.draft_definition.edges.map((e:any)=>({id:e.id,source:e.source_node_id,target:e.target_node_id,sourceHandle:e.source_handle||"success",targetHandle:e.target_handle||"input"})));setMessage(`${r.name} yüklendi.`);}catch(e){setMessage(String(e));}};
  const act=async(action:string)=>{try{if(action==="validate"){const r=await api("/api/v1/workflows/validate",{method:"POST",body:JSON.stringify(graph())});setMessage(r.valid?"Graf geçerli.":JSON.stringify(r.errors));return;}const headers={"X-CSRF-Token":csrf};if(action==="save"){const r=await api(`/api/v1/workflows/${workflowId}/draft`,{method:"PUT",headers,body:JSON.stringify({draft_revision:revision,graph:graph()})});setRevision(r.draft_revision);setMessage("Taslak kaydedildi.");return;}if(action==="publish"){await api(`/api/v1/workflows/${workflowId}/publish`,{method:"POST",headers,body:"{}"});setMessage("Sürüm atomik olarak yayınlandı.");return;}const r=await api(`/api/v1/workflows/${workflowId}/run`,{method:"POST",headers,body:JSON.stringify({trigger_data:{source:"editor-test"}})});setMessage(`Yürütme kuyruğa alındı: ${r.execution_id}`);const source=new EventSource(`/api/v1/executions/${r.execution_id}/events`);source.addEventListener("execution",event=>{const update=JSON.parse((event as MessageEvent).data);setExecution(update);if(["completed","failed","cancelled"].includes(update.status))source.close();});}catch(e){setMessage(String(e));}};
  const configure=(text:string)=>{try{const configuration=JSON.parse(text);setNodes(ns=>ns.map(n=>n.id===selected?{...n,data:{...n.data,configuration}}:n));setMessage("Yapılandırma güncellendi.");}catch{setMessage("Yapılandırma geçerli JSON olmalı.");}};
  return <main className="shell"><header><div><h1>FlowAPI</h1><span>Durable workflow studio</span></div><div className="session"><input value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Parola"/><button onClick={login}>Giriş</button></div></header>
  <div className="toolbar"><input className="workflow-id" value={workflowId} onChange={e=>setWorkflowId(e.target.value)} placeholder="Workflow UUID"/><button onClick={load}>Yükle</button><button onClick={()=>act("save")}>Kaydet</button><button onClick={()=>act("validate")}>Doğrula</button><button onClick={()=>act("run")}>Test et</button><button className="publish" onClick={()=>act("publish")}>Yayınla</button><span>rev {revision}</span></div>
  <section className="workspace"><aside className="palette"><h2>Düğümler</h2>{TYPES.map(type=><div className="palette-node" draggable key={type} onDragStart={e=>e.dataTransfer.setData("application/flowapi-node",type)}>{type.replaceAll("_"," ")}</div>)}</aside>
  <div className="canvas" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect="move";}} onDrop={e=>{e.preventDefault();const type=e.dataTransfer.getData("application/flowapi-node");if(!type)return;setNodes(ns=>[...ns,{id:crypto.randomUUID(),position:screenToFlowPosition({x:e.clientX,y:e.clientY}),data:{label:type.replaceAll("_"," "),nodeType:type,configuration:DEFAULTS[type]||{}}}]);}}><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_,n)=>setSelected(n.id)} fitView deleteKeyCode={["Backspace","Delete"]}><Background/><MiniMap/><Controls/></ReactFlow></div>
  <aside className="inspector"><h2>Yapılandırma</h2>{selectedNode?<><strong>{selectedNode.data.label}</strong><textarea key={`${selectedNode.id}-${JSON.stringify(selectedNode.data.configuration)}`} defaultValue={JSON.stringify(selectedNode.data.configuration,null,2)} onBlur={e=>configure(e.target.value)}/><div className="row"><button onClick={()=>setNodes(ns=>[...ns,{...selectedNode,id:crypto.randomUUID(),position:{x:selectedNode.position.x+40,y:selectedNode.position.y+40},selected:false}])}>Çoğalt</button><button className="danger" onClick={()=>{setNodes(ns=>ns.filter(n=>n.id!==selected));setEdges(es=>es.filter(e=>e.source!==selected&&e.target!==selected));setSelected(null);}}>Sil</button></div></>:<p>Bir düğüm seçin.</p>}<h2>Canlı yürütme</h2><pre>{execution?JSON.stringify(execution,null,2):"Henüz yürütme yok."}</pre></aside></section><footer>{message}</footer></main>;
}
export default function Home(){return <ReactFlowProvider><Studio/></ReactFlowProvider>;}
